// admin-v2/src/routes/(dashboard)/reports/+page.svelte
<script lang="ts">
  import Card from '$lib/components/Card.svelte';
  import Table from '$lib/components/Table.svelte';

  let { data, form } = $props();
</script>

<div class="space-y-4">
  <Card title="Filters" subtitle="Triage the queue">
    <form class="grid gap-3 md:grid-cols-[160px_160px_1fr_auto]" method="GET">
      <select name="status" class="rounded-lg border border-border bg-background px-3 py-2 text-sm text-slate-100 outline-none focus:border-primary">
        <option value="">All statuses</option>
        {#each ['pending', 'resolved', 'dismissed'] as status}<option value={status} selected={data.params.status === status}>{status}</option>{/each}
      </select>
      <select name="severity" class="rounded-lg border border-border bg-background px-3 py-2 text-sm text-slate-100 outline-none focus:border-primary">
        <option value="">All severities</option>
        {#each ['low', 'medium', 'high', 'critical'] as severity}<option value={severity} selected={data.params.severity === severity}>{severity}</option>{/each}
      </select>
      <select name="conventionId" class="rounded-lg border border-border bg-background px-3 py-2 text-sm text-slate-100 outline-none focus:border-primary">
        <option value="">All conventions</option>
        {#each data.conventions as convention}<option value={convention.id} selected={data.params.conventionId === convention.id}>{convention.name}</option>{/each}
      </select>
      <button class="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-accent">Apply</button>
    </form>
  </Card>
  <Card title="Reports" subtitle={`Total: ${data.reports.length}`}>
    {#if form?.error}<div class="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-100">{form.error}</div>{/if}
    <Table headers={['Type', 'Status', 'Reporter', 'Target', 'Description', 'Created', 'Actions']}>
      {#each data.reports as report}
        {@const reporter = Array.isArray(report.profiles) ? report.profiles[0]?.username : report.profiles?.username}
        {@const target = Array.isArray(report.reported) ? report.reported[0]?.username : report.reported?.username}
        {@const reportedFursuit = report.reported_fursuit}
        <tr>
          <td class="px-4 py-3 text-slate-200">{report.report_type}</td>
          <td class="px-4 py-3 capitalize text-slate-200">{report.status}</td>
          <td class="px-4 py-3 text-slate-200">{reporter ?? report.reporter_id}</td>
          <td class="px-4 py-3 text-slate-200">
            <div class="space-y-2">
              {#if report.reported_user_id}<div><span class="mr-2 text-xs text-muted">User</span><a href={`/players/${report.reported_user_id}`} class="rounded-lg border border-border px-2.5 py-1 text-xs font-semibold text-slate-100 transition hover:border-primary">{target ?? report.reported_user_id}</a></div>{/if}
              {#if report.reported_fursuit_id}<div class="space-y-1 text-sm"><div><span class="text-xs text-muted">Fursuit</span> <span>{reportedFursuit?.name ?? report.reported_fursuit_id}</span></div>{#if reportedFursuit?.owner_id}<div><span class="text-xs text-muted">Owner</span> <a href={`/players/${reportedFursuit.owner_id}`} class="text-xs font-semibold text-slate-100 underline decoration-border underline-offset-4 transition hover:text-primary">{reportedFursuit.owner?.username ?? reportedFursuit.owner_id}</a></div>{/if}</div>{/if}
              {#if !report.reported_user_id && !report.reported_fursuit_id}<span class="text-muted">-</span>{/if}
            </div>
          </td>
          <td class="px-4 py-3 text-slate-200">{#if report.description}<span class="line-clamp-2 max-w-xs text-sm">{report.description}</span>{:else}<span class="text-muted">-</span>{/if}</td>
          <td class="px-4 py-3 text-slate-200">{report.created_at ? new Date(report.created_at).toLocaleString() : '-'}</td>
          <td class="px-4 py-3">
            {#if report.status === 'resolved' || report.status === 'dismissed'}
              <span class="text-xs text-muted">Closed</span>
            {:else}
              <form class="space-y-2" method="POST" action="?/resolve">
                <input type="hidden" name="reportId" value={report.id} />
                <textarea name="resolutionNotes" placeholder="Resolution notes" class="w-48 rounded-lg border border-border bg-background px-2 py-1 text-xs text-slate-100 outline-none focus:border-primary"></textarea>
                <div class="flex gap-2">
                  <button name="status" value="resolved" class="rounded-lg bg-primary px-2.5 py-1 text-xs font-semibold text-slate-900 transition hover:bg-accent">Resolve</button>
                  <button name="status" value="dismissed" class="rounded-lg border border-border px-2.5 py-1 text-xs font-semibold text-slate-100 transition hover:border-primary">Dismiss</button>
                </div>
              </form>
            {/if}
          </td>
        </tr>
      {:else}
        <tr><td class="px-4 py-3 text-sm text-muted" colspan="7">No reports found.</td></tr>
      {/each}
    </Table>
  </Card>
</div>

// admin/app/(dashboard)/reports/page.tsx
import Link from 'next/link';

import { Card } from '@/components/card';
import { Table } from '@/components/table';
import { ReportFilters } from '@/components/report-filters';
import { ReportActions } from '@/components/report-actions';
import { fetchConventions, fetchReports } from '@/lib/data';
import { requireAdminDataContext } from '@/lib/auth';

type SearchParams = {
  status?: string;
  severity?: string;
  conventionId?: string;
};

export default async function ReportsPage({ searchParams }: { searchParams: SearchParams }) {
  const { supabase } = await requireAdminDataContext();
  const [reports, conventions] = await Promise.all([
    fetchReports(supabase, {
      status: searchParams.status,
      severity: searchParams.severity,
      conventionId: searchParams.conventionId,
    }),
    fetchConventions(supabase),
  ]);

  return (
    <div className="space-y-4">
      <Card
        title="Filters"
        subtitle="Triage the queue"
      >
        <ReportFilters
          conventions={conventions}
          initial={searchParams}
        />
      </Card>
      <Card
        title="Reports"
        subtitle={`Total: ${reports.length}`}
      >
        <Table
          headers={['Type', 'Status', 'Reporter', 'Target', 'Description', 'Created', 'Actions']}
        >
          {reports.map((report: any) => {
            const id = (report as any)?.id ?? '';
            const reporter = Array.isArray(report.profiles)
              ? report.profiles[0]?.username
              : (report.profiles as any)?.username;
            const target = Array.isArray(report.reported)
              ? report.reported[0]?.username
              : (report.reported as any)?.username;
            const reportedUserId = report.reported_user_id as string | null;
            const reportedFursuitId = report.reported_fursuit_id as string | null;
            const reportedFursuit = report.reported_fursuit as {
              id?: string | null;
              name?: string | null;
              owner_id?: string | null;
              owner?: { username?: string | null } | null;
            } | null;
            const fursuitOwnerId = reportedFursuit?.owner_id ?? null;
            const fursuitOwnerUsername = reportedFursuit?.owner?.username ?? null;

            return (
              <tr key={id}>
                <td className="px-4 py-3 text-slate-200">{report.report_type}</td>
                <td className="px-4 py-3 capitalize text-slate-200">{report.status}</td>
                <td className="px-4 py-3 text-slate-200">{reporter ?? report.reporter_id}</td>
                <td className="px-4 py-3 text-slate-200">
                  <div className="space-y-2">
                    {reportedUserId ? (
                      <div>
                        <span className="mr-2 text-xs text-muted">User</span>
                        <Link
                          href={`/players/${reportedUserId}`}
                          className="rounded-lg border border-border px-2.5 py-1 text-xs font-semibold text-slate-100 transition hover:border-primary"
                        >
                          {target ?? reportedUserId}
                        </Link>
                      </div>
                    ) : null}
                    {reportedFursuitId ? (
                      <div className="space-y-1 text-sm">
                        <div>
                          <span className="text-xs text-muted">Fursuit</span>{' '}
                          <span>{reportedFursuit?.name ?? reportedFursuitId}</span>
                        </div>
                        {fursuitOwnerId ? (
                          <div>
                            <span className="text-xs text-muted">Owner</span>{' '}
                            <Link
                              href={`/players/${fursuitOwnerId}`}
                              className="text-xs font-semibold text-slate-100 underline decoration-border underline-offset-4 transition hover:text-primary"
                            >
                              {fursuitOwnerUsername ?? fursuitOwnerId}
                            </Link>
                          </div>
                        ) : null}
                      </div>
                    ) : null}
                    {!reportedUserId && !reportedFursuitId ? (
                      <span className="text-muted">—</span>
                    ) : null}
                  </div>
                </td>
                <td className="px-4 py-3 text-slate-200">
                  {report.description ? (
                    <span className="line-clamp-2 max-w-xs text-sm">{report.description}</span>
                  ) : (
                    <span className="text-muted">—</span>
                  )}
                </td>
                <td className="px-4 py-3 text-slate-200">
                  {report.created_at ? new Date(report.created_at).toLocaleString() : '—'}
                </td>
                <td className="px-4 py-3">
                  {report.status === 'resolved' || report.status === 'dismissed' ? (
                    <span className="text-xs text-muted">Closed</span>
                  ) : (
                    <ReportActions reportId={id} />
                  )}
                </td>
              </tr>
            );
          })}
          {!reports.length ? (
            <tr>
              <td
                className="px-4 py-3 text-sm text-muted"
                colSpan={7}
              >
                No reports found.
              </td>
            </tr>
          ) : null}
        </Table>
      </Card>
    </div>
  );
}
